### PR TITLE
 Fixed #134 Now you can delete a note even if not saved

### LINKED ISSUE #134: Delete note after adding a new one
**Describe the bug**
After adding a new note and trying to delete the new note, it fails.

**To Reproduce**
1. Click on New Note button
2. After a new note is added, click on Delete button
4. Status message shows that note cannot be deleted

**Expected behavior**
Note should be deleted.

### PR DESCRIPTION
**Pull request by jesusbibieca**
Fixes #134 

Changes proposed in this pull request:
- Now you can delete a note even if the note is not saved in the DB
Basically, I check if the note is in the db before I call `removeNote` which will trigger an error since the `doc` doesn't exits yet. and instead I remove it from the list and I set the `New Note` to active again, so you can create a new note again.

### Test:
- Open the app
- Click on New Note
- Click on Delete Note
- Click on New Note

All these things should properly work.

### CODE REVIEW

File: app/components/StatusModal.js [hunk 1]
```diff
@@ -23,6 +23,7 @@ export default class StatusModal extends Component {
         break
       case NOTE_STATUS.NOTE_LOAD_SUCCESS:
       case NOTE_STATUS.NOTE_DELETE_SUCCESS:
+        this.props.setNewNoteDisabled(false)
```
Comment (jesusbibieca) [inline app/components/StatusModal.js]: Since this will call [this](https://github.com/abahmed/Deer/blob/develop/app/reducers/header.js#L9) at the end, it doesn't matter that I set it here since it will not change if it's `false` already. :man_shrugging:

File: app/actions/note.js [hunk 2]
```diff
@@ -97,13 +97,26 @@ export const deleteNote = () => (dispatch, getState) => {
...
   const state = getState().noteReducer
   const noteIndex = state.activeNoteIndex
-  removeNote(state.notes[noteIndex].id,
-    state.notes[noteIndex].rev).then((result) => {
-    dispatch(deleteNoteFromList(result.id))
-    dispatch(setActiveNoteIndex(ACTIONS.NOT_SELECTED_NOTE))
-    dispatch(setNoteStatus(NOTE_STATUS.NOTE_DELETE_SUCCESS))
-  }).catch((err) => {
-    dispatch(setNoteStatus(NOTE_STATUS.NOTE_DELETE_FAIL))
+  try {
```
Comment (jesusbibieca) [inline app/actions/note.js]: If there's a better approach to this, I'd like to know... So I can improve it :)

File: app/components/StatusModal.js (hunk 1 above)
Comment (abahmed) [reply app/components/StatusModal.js]: Yes, you are right! :+1:

File: app/actions/note.js (hunk 2 above)
Comment (abahmed) [reply app/actions/note.js]: I think this is not needed as you already have two catches. @enzo-beltrami What do you think?

Comment (enzo-beltrami) [reply app/actions/note.js]: We have some logic under the second catch so if something goes wrong there it'll throw an Exception that will get caught in this catch but i think we should run  `    dispatch(setNoteStatus(NOTE_STATUS.NOTE_DELETE_FAIL))
` to give the user some feedback.

File: app/actions/note.js [hunk 3]
```diff
@@ -97,13 +97,26 @@ export const deleteNote = () => (dispatch, getState) => {
...
+      if (err) {
+        dispatch(deleteNoteFromList(state.notes[noteIndex].id))
+        dispatch(setActiveNoteIndex(ACTIONS.NOT_SELECTED_NOTE))
+        dispatch(setNoteStatus(NOTE_STATUS.NOTE_DELETE_SUCCESS))
+      }
+    })
+  } catch (err) {
     logger.error('Unable to remove note ' + err)
-  })
+  }
```
Comment (jesusbibieca) [inline app/actions/note.js]: @enzo-beltrami you mean here?
